### PR TITLE
Set web component as properties, not attributes [breaking change]

### LINKED ISSUE #730: Web component properties do not seem to accept objects or arrays
Example:

```
  static properties = {
    value1: {type: Object},
    value2: {type: Array},
  };
```

I'm not sure if I'm doing something wrong here, but when I try to pass in an Array or Object, I get undefined.

### PR DESCRIPTION
**Pull request by wwwillchen**
Fixes #730.

**Breaking change**: Web components are now set via DOM properties and not attributes. This means you can _not_ use Lit's attribute API, e.g. 

```ts
  static properties = {
    value: {type: Number},
    incrementEventHandlerId: {attribute: 'increment-event', type: String},
  };
```

I mixed up [DOM attributes and DOM properties](https://jakearchibald.com/2024/attributes-vs-properties/#value-types:~:text=elements%2C%20not%20properties.-,Value%20types,-In%20order%20to) and only primitive types, e.g. string, number, boolean, worked when I erroneously set the web component properties as DOM attributes. [Lit's default converter](https://lit.dev/docs/components/properties/#conversion-type) worked for the primitive types.

### CODE REVIEW

File: mesop/web/src/component_renderer/component_renderer.ts [hunk 1]
```diff
@@ -210,7 +210,7 @@ export class ComponentRenderer {
         // We should have checked this in Python, but just in case
         // we will check the attribute name right before using it.
         checkAttributeNameIsSafe(key);
```
Comment (richard-to) [inline mesop/web/src/component_renderer/component_renderer.ts:212]: Do we need to check attribute name still if we're using properties?

Comment (richard-to) [reply mesop/web/src/component_renderer/component_renderer.ts:212]: Also above there is boolean check. Does that apply to the properties change as well?

**Review by richard-to — APPROVED** [review]

File: mesop/web/src/component_renderer/component_renderer.ts (hunk 1 above)
Comment (wwwillchen) [reply mesop/web/src/component_renderer/component_renderer.ts]: good questions - I'm not 100% sure if the attribute name check is still needed. When I experimented with it, things like `onclick` which are unsafe as an attribute (e.g. evals a string as a JS function) don't seem to have the same issue as a property, but I'm not sure if this is true across all browsers. Also the src* checks still seem valid for property. Since it's always easier to remove a check and I haven't heard anyone complain yet about these checks, I'll leave in the name check.

The boolean check, though, I think we can remove - I tested it out and I don't see an issue with always setting the boolean property.
